# Generated by Django 5.2.6 on 2025-09-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_isfeatured_product_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_viewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
